<a href="https://colab.research.google.com/github/TadieB/pytorch-collab/blob/main/linearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression

In [16]:
import numpy as np
import torch


# Training Data

In [13]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91,88,64],
                   [87, 134, 58],
                   [102,43,37],
                   [69,96,70]],dtype='float32'
)

In [7]:
# Targets (apples, oranges)
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]],dtype='float32')

# Model

In [8]:
# Weights and biases
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 1.3537, -0.6997,  0.2358],
        [ 0.6098, -0.3540,  0.1082]], requires_grad=True)
tensor([ 0.8047, -1.6870], requires_grad=True)


In [14]:
def model(x):
  return x @ w.t()+b

# @ represents matrix multiplication in pyTorch, .t is the transpose of a tensor

# Predictions

In [23]:
# w and inputs should be the same type tensors or numpy arrays,
inputs = torch.tensor(inputs)

<ipython-input-23-76016b2a2be4>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs = torch.tensor(inputs)


In [25]:
preds = model(inputs)
print(preds)

tensor([[ 62.8825,  23.7625],
        [ 77.5067,  29.5768],
        [ 38.4912,  10.2064],
        [117.5170,  49.2923],
        [ 43.5430,  13.9789]], grad_fn=<AddBackward0>)


In [26]:
print(targets)
#compare preds with targets

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [27]:
targets = torch.tensor(targets)

# Loss Function

In [30]:
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [31]:
loss = mse(preds, targets)

print(loss)

tensor(5269.7837, grad_fn=<DivBackward0>)


# Compute Gradients