<a href="https://colab.research.google.com/github/TadieB/pytorch-collab/blob/main/linearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression

In [16]:
import numpy as np
import torch


# Training Data

In [13]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91,88,64],
                   [87, 134, 58],
                   [102,43,37],
                   [69,96,70]],dtype='float32'
)

In [7]:
# Targets (apples, oranges)
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]],dtype='float32')

# Model

In [8]:
# Weights and biases
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 1.3537, -0.6997,  0.2358],
        [ 0.6098, -0.3540,  0.1082]], requires_grad=True)
tensor([ 0.8047, -1.6870], requires_grad=True)


In [14]:
def model(x):
  return x @ w.t()+b

# @ represents matrix multiplication in pyTorch, .t is the transpose of a tensor

# Predictions

In [23]:
# w and inputs should be the same type tensors or numpy arrays,
inputs = torch.tensor(inputs)

<ipython-input-23-76016b2a2be4>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs = torch.tensor(inputs)


In [25]:
preds = model(inputs)
print(preds)

tensor([[ 62.8825,  23.7625],
        [ 77.5067,  29.5768],
        [ 38.4912,  10.2064],
        [117.5170,  49.2923],
        [ 43.5430,  13.9789]], grad_fn=<AddBackward0>)


In [26]:
print(targets)
#compare preds with targets

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [27]:
targets = torch.tensor(targets)

# Loss Function

In [30]:
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [31]:
loss = mse(preds, targets)

print(loss)

tensor(5269.7837, grad_fn=<DivBackward0>)


# Compute Gradients

In [32]:
loss.backward()

In [33]:
print(w)
print(w.grad)

tensor([[ 1.3537, -0.6997,  0.2358],
        [ 0.6098, -0.3540,  0.1082]], requires_grad=True)
tensor([[ -235.9073, -2447.0210, -1044.9994],
        [-5310.1064, -7078.1909, -4115.5972]])


In [35]:
# reset gradients to zero lest pytorch accumulates , gradients.

w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


# gradient descent: adjust weights


In [37]:
preds = model(inputs)
print(preds)

tensor([[ 62.8825,  23.7625],
        [ 77.5067,  29.5768],
        [ 38.4912,  10.2064],
        [117.5170,  49.2923],
        [ 43.5430,  13.9789]], grad_fn=<AddBackward0>)


In [38]:
loss = mse(preds, targets)
loss

tensor(5269.7837, grad_fn=<DivBackward0>)

In [39]:
# compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -235.9073, -2447.0210, -1044.9994],
        [-5310.1064, -7078.1909, -4115.5972]])
tensor([ -8.2119, -66.6366])


In [40]:
# adjust the weights

with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  #reset grads, not the weights lest affect future grad computations
  w.grad.zero_()
  b.grad.zero_()

In [41]:
print(w)
print(b)

tensor([[ 1.3560, -0.6752,  0.2462],
        [ 0.6629, -0.2832,  0.1493]], requires_grad=True)
tensor([ 0.8047, -1.6864], requires_grad=True)


# claculate loss

In [42]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(4334.9761, grad_fn=<DivBackward0>)


# Train for Multiple Epochs

In [43]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad*1e-5
    b -= b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()


In [44]:
preds = model(inputs)
loss = mse(preds, targets)

print(loss)


tensor(701.3605, grad_fn=<DivBackward0>)


In [45]:
preds

tensor([[ 67.3044,  76.5914],
        [ 88.2699, 102.3743],
        [ 88.6059, 118.9776],
        [ 79.1557,  74.9132],
        [ 78.7359,  99.6540]], grad_fn=<AddBackward0>)

In [46]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Linear Regression Using PyTorch built-ins

In [54]:
import torch.nn as nn

In [53]:
# input (temp,rainfall, humidity)
inputs = np.array([[73,67,43],
                   [91,88,64],
                  [87,134,58],
                   [102, 43,37],
                    [69,96,70],
                     [73,67,43],
                   [91,88,64],
                    [87,134,58],
                     [102, 43,37],
                   [69,96,70],
                    [73,67,43],
                     [91,88,64],
                   [87,134,58],
                    [102, 43,37],
                     [69,96,70]], dtype='float32')

targets = np.array([[56,70],[81,101],[119,133],
                    [22,37],[103,119],[56,70],
                    [81,101],[119,133],[22,37],
                    [103,119],[56,70],[81,101],
                    [119,133],[22,37],[103,119]], dtype = 'float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [56]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [57]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Dataset and DataLoader

In [58]:
from torch.utils.data import TensorDataset

In [59]:
# Define dataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [60]:
from torch.utils.data import DataLoader

In [70]:
# define dataloader: batch size = parts of a dataset taken for training, epoch = iteation
batch_size = 5
train_dl = DataLoader(train_ds,batch_size, shuffle = True)
#it shuffles first, then create batches

In [69]:
# at each iteration data loade returns one batch of data, with the given batch size.
for xb, yb in train_dl:

  print(xb)
  print(yb)
  break

tensor([[ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.]])
tensor([[ 56.,  70.],
        [103., 119.],
        [119., 133.],
        [ 81., 101.],
        [ 56.,  70.]])


# nn.Linear

In [71]:
# define model
model = nn.Linear(3,2)

print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0703, -0.2514, -0.1176],
        [-0.5081, -0.4481, -0.3377]], requires_grad=True)
Parameter containing:
tensor([-0.3656,  0.2580], requires_grad=True)


In [74]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0703, -0.2514, -0.1176],
         [-0.5081, -0.4481, -0.3377]], requires_grad=True),
 Parameter containing:
 tensor([-0.3656,  0.2580], requires_grad=True)]

In [75]:
preds = model(inputs)
preds

tensor([[ -17.1357,  -81.3730],
        [ -23.6198, -107.0189],
        [ -34.7608, -123.5714],
        [  -8.3569,  -83.3287],
        [ -27.8836, -101.4510],
        [ -17.1357,  -81.3730],
        [ -23.6198, -107.0189],
        [ -34.7608, -123.5714],
        [  -8.3569,  -83.3287],
        [ -27.8836, -101.4510],
        [ -17.1357,  -81.3730],
        [ -23.6198, -107.0189],
        [ -34.7608, -123.5714],
        [  -8.3569,  -83.3287],
        [ -27.8836, -101.4510]], grad_fn=<AddmmBackward0>)

# Loss Function

In [76]:
import torch.nn.functional as F

In [77]:
loss_fn = F.mse_loss

In [78]:
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(25308.0762, grad_fn=<MseLossBackward0>)


# Optimizer

In [79]:
opt = torch.optim.SGD(model.parameters(),lr =1e-5)

# Train Model

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):

  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch+1)%10==0:
      print('Epoch')