<a href="https://colab.research.google.com/github/TadieB/pytorch-collab/blob/main/warmup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)
print(t1)
t1.dtype
t1.shape

tensor(4.)


torch.Size([])

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([3, 4.])
t2.dtype
print(t2)
t2.shape

tensor([3., 4.])


torch.Size([2])

In [6]:
t3 = torch.tensor([[3,4],[4,2.]])
t3.shape

torch.Size([2, 2])

In [17]:
t4 = torch.tensor([[[2,3.],[1,2]],[[3,3],[4,7]]])

print(t4)

tensor([[[2., 3.],
         [1., 2.]],

        [[3., 3.],
         [4., 7.]]])


In [18]:
t4.shape

torch.Size([2, 2, 2])

# Gradients

In [13]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(1., requires_grad=True)

y = w*x+b

In [16]:
y

tensor(13., grad_fn=<AddBackward0>)

In [14]:
# compute derivatives
y.backward()

# display gradients

In [15]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)


dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# Interoperability with Numpy

In [20]:
import numpy as np

In [21]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [22]:
# convert the nmpy aray to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [24]:
x.dtype,       y.dtype

(dtype('int64'), torch.int64)

In [25]:
# convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

# Commit and upload the notebook